"""Add Tasklist model

Revision ID: 6a3962bcb7c0
Revises: 9d82cece485c
Create Date: 2020-07-01 17:37:57.184756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a3962bcb7c0'
down_revision = '9d82cece485c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasklist',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('remote_id', sa.String(), nullable=True),
                    sa.Column('source_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['source_id'], ['tasklist_source.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasklist')
    # ### end Alembic commands ###
